[workspace]
members = ["plait", "plait-macros"]
resolver = "3"

[workspace.dependencies]
actix-web = { version = "4", default-features = false }
axum = { version = "0.8", default-features = false }
convert_case = "0.10"
itoa = "1"
percent-encoding = "2"
plait-macros = { version = "0.9.0", path = "./plait-macros" }
proc-macro2 = "1"
quote = "1"
rocket = { version = "0.5", default-features = false }
ryu = "1"
syn = { version = "3", features = ["full", "visit-mut"] }
